---
all:
  children:

    dns:
      hosts:
        dns-01:
          ansible_host: 172.16.30.11
        dns-02:
          ansible_host: 172.16.30.12

    nexus:
      hosts:
        nexus-01:
          ansible_host: 172.16.30.15

    vault:
      hosts:
        vault-01:
          ansible_host: 172.16.30.21
        vault-02:
          ansible_host: 172.16.30.22
        vault-03:
          ansible_host: 172.16.30.23

    haproxy:
      hosts:
        haproxy-01:
          ansible_host: 172.16.20.11
        haproxy-02:
          ansible_host: 172.16.20.12

    k8s_master:
      hosts:
        k8s-master-01:
          ansible_host: 172.16.30.31
        k8s-master-02:
          ansible_host: 172.16.30.32
        k8s-master-03:
          ansible_host: 172.16.30.33

    k8s_worker:
      hosts:
        k8s-worker-plat:
          ansible_host: 172.16.30.40
        k8s-worker-01:
          ansible_host: 172.16.30.41
        k8s-worker-02:
          ansible_host: 172.16.30.42
        k8s-worker-03:
          ansible_host: 172.16.30.43

    minio:
      hosts:
        minio-01:
          ansible_host: 172.16.30.50

    cicd:
      hosts:
        cicd-01:
          ansible_host: 172.16.30.60

    monitor:
      hosts:
        monitor-01:
          ansible_host: 172.16.30.70

    siem:
      hosts:
        siem-01:
          ansible_host: 172.16.30.80

    # 편의 그룹: k8s 전체
    k8s:
      children:
        k8s_master:
        k8s_worker:
