name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'Terraform/**'
  workflow_dispatch:       # 수동 실행도 가능하도록 설정

jobs:
  terraform:
    runs-on: self-hosted   # kosa1 runner 사용함을 의미

    steps:
      # 1. 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Terraform 설치
      - name: Setup Terraform
        run: echo "Terraform already installed"

      # 3. terraform.tfvars 생성 (Secret에서 가져옴)
      - name: Create tfvars
        run: |
          cat > Terraform/terraform.tfvars << TFVARS
          proxmox_api_token = "${{ secrets.PROXMOX_API_TOKEN }}"
          ssh_public_keys = [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINrok3kv0IdHh5eQEJbZ9JdaLs8ZVfc9/G7LCJp/o8u3 kosa-soyeon"
          ]
          TFVARS

      # 4. Terraform 초기화
      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: Terraform

      # 6. Terraform Apply (main 브랜치 push 할 때만 실행)
      - name: Terraform Apply
        run: terraform apply -auto-approve -parallelism=2  #> [!TIP]
        working-directory: Terraform                       # ceph 스토리지는 ubuntu template으로부터 vm을 clone할 때 잠금(lock)을 건다.
                                                           # 동시에 여러 vm을 clone하면 서로 lock 해제를 기다리다가 timeout이 나서 오류가 발생
                                                           # 이를 방지하기 위해 -parallelism=2 옵션을 추가해준 것.
 
